import type { KiyoMapData } from "@/lib/kiyo-map/schema";
import { KIYO_MAP_WORKSPACE_NAME } from "@/lib/kiyo-map/branding";

const now = "2026-07-01T09:00:00.000Z";
const weekAgo = "2026-06-24T10:00:00.000Z";

export const DEFAULT_KIYO_MAP_DATA: KiyoMapData = {
  version: 1,
  workspace: {
    name: KIYO_MAP_WORKSPACE_NAME,
    icon: "map",
  },
  categories: [
    "アイディア",
    "HR/労務",
    "AI推進",
    "ブランディング",
    "IT/セキュリティ",
    "総務",
  ],
  projects: [
    {
      id: "p1",
      title: "チャレンジ評価制度のスライド",
      status: "in_progress",
      category: "HR/労務",
      priority: "A",
      progress: 60,
      deadline: "2026-07-15",
      nextAction: "③支援部分を詰める",
      memo: "40点配分は固まった。残りは事例スライドとFAQ想定問答。",
      createdAt: weekAgo,
      updatedAt: now,
      completedAt: null,
      history: [
        {
          date: weekAgo,
          content: "案件を作成",
        },
        {
          date: now,
          content: "進捗 60% に更新",
        },
      ],
      relatedProjectIds: ["p2"],
      relatedNotes: "前回MTG: 評価基準の説明は経営層向けに簡潔に。",
      relatedAiKnowledge: null,
    },
    {
      id: "p2",
      title: "評価基準の説明資料",
      status: "in_progress",
      category: "HR/労務",
      priority: "B",
      progress: 35,
      deadline: "2026-07-20",
      nextAction: "キックオフ用1枚サマリを作る",
      memo: "制度概要と運用フローの2本立てで整理中。",
      createdAt: weekAgo,
      updatedAt: now,
      completedAt: null,
      history: [{ date: weekAgo, content: "案件を作成" }],
      relatedProjectIds: ["p1"],
      relatedNotes: "",
      relatedAiKnowledge: null,
    },
    {
      id: "p3",
      title: "キックオフ資料の全面改訂",
      status: "done",
      category: "ブランディング",
      priority: "S",
      progress: 100,
      deadline: "2026-06-30",
      nextAction: "",
      memo: "全社共有済み。フィードバックは次四半期に反映。",
      createdAt: "2026-05-10T09:00:00.000Z",
      updatedAt: "2026-06-28T15:00:00.000Z",
      completedAt: "2026-06-28T15:00:00.000Z",
      history: [
        { date: "2026-06-28T15:00:00.000Z", content: "完了" },
      ],
      relatedProjectIds: [],
      relatedNotes: "",
      relatedAiKnowledge: null,
    },
    {
      id: "p4",
      title: "部門ヒアリング計画",
      status: "in_progress",
      category: "AI推進",
      priority: "A",
      progress: 20,
      deadline: "2026-08-01",
      nextAction: "対象部門リストを確定",
      memo: "AI活用促進プロジェクトのヒアリング設計。",
      createdAt: weekAgo,
      updatedAt: now,
      completedAt: null,
      history: [{ date: weekAgo, content: "新規着手" }],
      relatedProjectIds: [],
      relatedNotes: "",
      relatedAiKnowledge: null,
    },
    {
      id: "p5",
      title: "社内FAQボット試作",
      status: "idea",
      category: "AI推進",
      priority: "B",
      progress: 0,
      deadline: null,
      nextAction: "要件を3行で書き出す",
      memo: "問い合わせ削減の PoC 案。",
      createdAt: weekAgo,
      updatedAt: weekAgo,
      completedAt: null,
      history: [{ date: weekAgo, content: "アイディアとして登録" }],
      relatedProjectIds: [],
      relatedNotes: "",
      relatedAiKnowledge: null,
    },
    {
      id: "p6",
      title: "マスコット新施策",
      status: "on_hold",
      category: "ブランディング",
      priority: "C",
      progress: 15,
      deadline: "2026-07-10",
      nextAction: "グッズ担当と再調整",
      memo: "グッズ担当との調整が難航。",
      createdAt: weekAgo,
      updatedAt: now,
      completedAt: null,
      history: [{ date: now, content: "保留に変更" }],
      relatedProjectIds: [],
      relatedNotes: "担当者変更の可能性あり。",
      relatedAiKnowledge: null,
    },
    {
      id: "p7",
      title: "端末セキュリティ棚卸し",
      status: "in_progress",
      category: "IT/セキュリティ",
      priority: "A",
      progress: 45,
      deadline: "2026-07-25",
      nextAction: "未登録端末リストを回収",
      memo: "全社展開前の最終確認。",
      createdAt: weekAgo,
      updatedAt: now,
      completedAt: null,
      history: [{ date: weekAgo, content: "案件を作成" }],
      relatedProjectIds: [],
      relatedNotes: "",
      relatedAiKnowledge: null,
    },
    {
      id: "p8",
      title: "備品発注フロー見直し",
      status: "idea",
      category: "総務",
      priority: "C",
      progress: 0,
      deadline: null,
      nextAction: "現行フローを図示",
      memo: "",
      createdAt: weekAgo,
      updatedAt: weekAgo,
      completedAt: null,
      history: [{ date: weekAgo, content: "アイディアとして登録" }],
      relatedProjectIds: [],
      relatedNotes: "",
      relatedAiKnowledge: null,
    },
  ],
  inbox: [],
  monthlyTopics: [],
};
